trivia2/trivia_project/trivia/urls.py
from django.urls import path
from . import views

app_name = 'trivia'

urlpatterns = [
    path('', views.trivia_view, name='trivia'),
    path('restart/', views.restart_game, name='restart'),
]

trivia2/trivia_project/trivia_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trivia.urls')),
]

trivia2/trivia_project/trivia/models.py
from django.db import models

class Question(models.Model):
    text = models.CharField(max_length=255)

    def __str__(self):
        return self.text

class Option(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

trivia2/trivia_project/trivia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound
from .models import Question

def trivia_view(request):
    if request.method == 'POST':
        # Procesar la respuesta del usuario
        question_id = request.POST.get('question_id')
        selected_option_id = request.POST.get('answer')
        
        try:
            question = Question.objects.get(pk=question_id)
            correct_option = question.option_set.get(is_correct=True)
            
            if selected_option_id == str(correct_option.id):
                message = "¡Correcto!"
                # Obtener la siguiente pregunta
                next_question = Question.objects.filter(id__gt=question_id).order_by('id').first()
                if next_question:
                    # Actualizar el current_question_id en la sesión
                    request.session['current_question_id'] = next_question.id
                else:
                    # Si no hay más preguntas, eliminar el current_question_id de la sesión
                    del request.session['current_question_id']
                    return render(request, 'trivia/trivia_game.html', {'message': "¡Felicidades! Has completado todas las preguntas. ¿Deseas volver a comenzar?"})
            else:
                message = f"Incorrecto. La respuesta correcta era: {correct_option.text}"
        except Question.DoesNotExist:
            return HttpResponseNotFound("La pregunta no existe.")
        except correct_option.DoesNotExist:
            return HttpResponseNotFound("La opción correcta para esta pregunta no existe.")
        
        return render(request, 'trivia/answer.html', {'message': message})
    
    # Obtener la pregunta actual
    current_question_id = request.session.get('current_question_id')
    if current_question_id:
        try:
            current_question = Question.objects.get(id=current_question_id)
        except Question.DoesNotExist:
            return HttpResponseNotFound("La pregunta no existe.")
    else:
        # Si no hay current_question_id en la sesión, obtener la primera pregunta
        current_question = Question.objects.first()
        if current_question:
            request.session['current_question_id'] = current_question.id
    
    # Obtener las opciones relacionadas con la pregunta actual
    options = current_question.option_set.all()

    return render(request, 'trivia/trivia_game.html', {'question': current_question, 'options': options})

def restart_game(request):
    # Eliminar el current_question_id de la sesión para reiniciar el juego
    if 'current_question_id' in request.session:
        del request.session['current_question_id']
    return redirect('trivia:trivia')

trivia2/trivia_project/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Trivia{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body style="display: flex; flex-direction: column; min-height: 100vh;">
    {% include 'header.html' %}

    <div class="content">
        {% block content %}{% endblock %}
    </div>

    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

trivia2/trivia_project/templates/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
        <span class="text-muted">Derechos de autor &copy; 2024. Todos los derechos reservados.</span>
    </div>
</footer>

trivia2/trivia_project/templates/header.html
<nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img width="25" height="25" src="https://img.icons8.com/external-tal-revivo-duo-tal-revivo/25/external-superpowers-app-is-a-tool-to-help-and-learn-about-your-individual-superpowers-logo-duo-tal-revivo.png" alt="external-superpowers-app-is-a-tool-to-help-and-learn-about-your-individual-superpowers-logo-duo-tal-revivo"/>
        Trivia
      </a>
    </div>
</nav>

trivia2/trivia_project/trivia/templates/trivia/answer.html
{% extends 'base.html' %}

{% block title %}Answer{% endblock %}

{% block content %}
    <div class="container text-center">
        <h1 class="text-primary">{{ message }}</h1>
        <a href="{% url 'trivia:trivia' %}" class="btn btn-secondary mt-3">Volver a Trivia</a>
    </div>
{% endblock %}

trivia2/trivia_project/trivia/templates/trivia/trivia_game.html
{% extends 'base.html' %}

{% block title %}Answer{% endblock %}

{% block content %}
    <div class="container text-center">
        {% if question %}
        <h1 class="mt-5">Pregunta:</h1>
        <p class="lead">{{ question.text }}</p>
        <form method="post" action="{% url 'trivia:trivia' %}" class="mt-4">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{ question.id }}">
            {% for option in options %}
            <div class="form-check">
                <input class="form-check-input" type="radio" id="option_{{ option.id }}" name="answer" value="{{ option.id }}">
                <label class="form-check-label" for="option_{{ option.id }}">{{ option.text }}</label>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3">Enviar</button>
        </form>
        {% else %}
        <p class="mt-5">¡Felicidades! Has completado todas las preguntas.</p>
        <form method="post" action="{% url 'trivia:restart' %}" class="mt-4">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Volver a comenzar</button>
        </form>
        {% endif %}
    </div>
{% endblock %}